In [1]:
import pandas as pd

In [5]:
tabla = "tabla.html"
df = pd.read_html(tabla)[0]
df

  Entrenador Tipo Fuego Tipo Planta  Tipo Agua
0       Rojo  Charizard    Venusaur  Blastoise
1       Azul   Arcanine   Exeggutor   Gyarados
2     Cintia  Magmortar    Roserade    Milotic

In [10]:
tablas = pd.read_html("datos_html_festival.html")
print("tablas detectadas: ", len(tablas))

for i, tabla in enumerate(tablas, start=1):
    print(i)
    display(tabla)

tablas detectadas:  2
1

  Escenario         Artista   Hora       Genero
0     Solar       Luna Byte  18:30  Electronica
1      Neón  Los Dataframes  19:15        Indie
2    Aurora     SQL Sisters  20:00        Synth
3     Solar     Pandas Crew  21:00         Funk
4      Neón    Null Hunters  22:10         Rock
5      test     Pandas Crew  21:00         Funk
6     test2    Null Hunters  22:10         Rock

2

            producto   categoria  precio_eur  unidades
0      Camiseta Glow        Ropa          20        45
1     Tote Bag Pixel  Accesorios          12        60
2       Sticker Pack  Accesorios           5       120
3        Gorra Night        Ropa          15        38
4  Vaso Reutilizable       Hogar           8        72